### PR TITLE
Added chefspec tests do drush recipe

### PR DESCRIPTION
**Pull request by cthalmann**
All recipes in our cookbooks need to have tests. After this PR the drush recipe will have ChefSpec tests, and that will finish ChefSpec test writing for this cookbook! 

Expected output:
```
cthalmann@blue:~/githubRepos/osl-drupal$ rake
Running RuboCop...
Inspecting 8 files
........

8 files inspected, no offenses detected
chef exec foodcritic --epic-fail any .

chef exec rspec

osl-drupal::default
  centos 6.7
    converges successfully
  centos 7.2.1511
    converges successfully

osl-drupal::drush
  centos 6.7
    converges successfully
    should include recipes
    should create yum_repository "drush"
    should install package "drush"
  centos 7.2.1511
    converges successfully
    should include recipes
    should create yum_repository "drush"
    should install package "drush"

Finished in 16 seconds (files took 2.39 seconds to load)
10 examples, 0 failures


ChefSpec Coverage report generated...

  Total Resources:   2
  Touched Resources: 2
  Touch Coverage:    100.0%

You are awesome and so is your test coverage! Have a fantastic day!
```

### CODE REVIEW

**Comment by jldugger** [comment]
```
$ knife search node 'recipes:osl-drupal'
0 items found
```

Do we use or intend to use this cookbook ever?

**Comment by ramereth** [comment]
@jldugger good point. I had forgotten to check to see if we had. I'd be fine with decommissioning this cookbook.

**Comment by ramereth** [comment]
@jldugger actually, I take that back. this is used on apereo although I just had to remove it due to the repo being gone on C6. Either way we need to come up with a plan on this.

**Comment by jldugger** [comment]
In that case, we may as well merge this, make an issue noting it doesn't work on some platforms, and revisit that when it becomes important to our customers.

**Pull request merged**
